@host = http://localhost:3000/api/users
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcwMjE4NjE5MiwiZXhwIjoxNzAyMjIyMTkyfQ.MLmJ7FzSq6q8BuuTBKZ01J0th1EqrNVA5nFCotAtBmM

###회원 가입
POST {{host}}/signup
Content-Type: application/json

{
   "email": "test@naver.com",
   "password": "1234",
   "passwordConfirm": "1234",
   "name":"관리자"
}

###로그인
POST {{host}}/signin
Content-Type: application/json

{
   "email": "test@naver.com",
   "password": "1234"
}

###내정보 조회
GET {{host}}/me
Authorization: Bearer {{accessToken}}