@host = http://localhost:3000/api/products
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTcwMjE3NDk0MywiZXhwIjoxNzAyMjEwOTQzfQ.ZWxeppaTae-1Z0p2ZoVqP6gvZVstSZu1QV7hRRzvuxM

### 상품 생성
POST {{host}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
   "title": "테스트용 타이틀2",
   "description" : "테스트 내용2"
}

### 상품 조회
GET {{host}}
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 단일 상품 조회
GET {{host}}/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}


### 상품 수정
PUT {{host}}/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "수정된 제목입니다", 
  "description": "수정된 내용입니다", 
  "status": "SOLD_OUT"
}

### 상품 삭제

DELETE {{host}}/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}
